### ISSUE TITLE
请教关于用 issue 写博客

### ISSUE THREAD

**Issue by hadeshe93** [ShannonChenCHN/eureka#100]
@ShannonChenCHN 博主你好，想请教一下如下问题。

1. 我看到你代码仓库里面和 issue 版面都有你的博文，两者是有关联的关系的吗？代码仓库的文章能否直接同步到 issue 中？
2. 如果你在 issue 中发布过的文章，在某一天发现有要修改的地方，是否就直接在上面改动，而没有 git 管理的功能？

**Comment by ShannonChenCHN** [comment]
据我所知，目前 issues 是没有版本控制的，代码仓库是有 git 版本管理的，而且两者之间也没有什么直接关系，一个是存代码的，一个是问题追踪用的。

因为我是最开始在 issues 上写的，后来有些是比较长的文章在本地写的，然后上传到仓库中的，所以现在两种形式都存在。


用 issues 写的特点是：
- 方便，快捷，写完后马上就能看到效果，而且也容易改，在手机上编辑也很方便，但是因为没有版本控制，所以如果手误，删掉了，或者没保存，就很头疼了
- 比较短的、临时的文章比较适合写在 issues 里面，一些初步的未成形的想法也可以先写在 issues 里面，等后面再完善

写在 repo 里的特点是：
- 有版本控制
- 相对来说，比较正式
- 可以离线写，没有网也可以
- 上传图片方便

**Comment by ShannonChenCHN** [comment]
@hadeshe93 对了，你是怎么看到我的这个 GitHub 博客的，方便告诉我一下吗？
